### ISSUE TITLE
Exception raised with unclear error message

### ISSUE THREAD

**Issue by olynch** [mikeshulman/narya#27]
I'm working off of the latest narya, and this fails to compile:

```
def Composite (a : Type) (x y z : a) (f : Id a x y) (g : Id a y z) : Type := sig (
  h : Id a x z,
  isComposite : Id (Id a) x y f x z h (refl x) g
)

def PreCat : Type := sig (
  ob : Type,
  compose : (x y z : ob) → (f : Id ob x y) -> (g : Id ob y z) -> Composite ob x y z f g
)

def Updated (s : Type) (old : s) (a : Type) : Type := sig (
  new : s,
  diff : Id s old new,
  result : a
)

def State (s : PreCat) (a : Type) : Type := sig (
  run : (old : s.ob) -> Updated s.ob old a
)
```

I get:

```
Fatal error: exception Invalid_argument("index_of_int")
```

**Comment by olynch** [comment]
Ah! I have to instead use `(s .ob)`. I think that it would be good to either support the very common syntax without a space, or give a better error message in this case.

**Comment by mikeshulman** [comment]
I've agonized over this, but I don't see a good way to support the syntax without a space, since the existing meaning of `s.ob` is the definition `ob` in the namespace `s`.  In theory, an identifier like `a.b.c.d` could cause Narya to check both whether there is a definition `d` in namespace `a.b.c`, and whether there is a definition `c` in namespace `a.b` that has a field `d`, and choose one that exists, with some behavior in case both exist, but that's a bit too DWIMmy for my taste.  I believe Agda has this same behavior with field projections.

However, the specific error message you mention is certainly wrong!  The message should be something like `undefined constant: s.ob`.  I'll look into it; I suspect what's happening is that it's getting mixed up with the syntax `x.0` for faces of a cube variable.

**Comment by mikeshulman** [comment]
(Which isn't to say I'm deadset against supporting the spaceless syntax, if anyone wants to make a case for it.)

**Comment by mikeshulman** [comment]
Another option would be to use different characters to separate namespaces and fields.  I'm not opposed to this in principle, but I haven't thought of a pair of characters to use that I like the look of sufficiently.  Dots are just really good for both.

**Comment by mikeshulman** [comment]
Ok, I fixed the bug with the error message.  (Another lesson in the advantages of `option` and `result` over unchecked exceptions: I was throwing one exception but catching a different one.  I switched to using `option` instead.)  And while I was at it, I added a hint that tries to detect this mistake.  With your code, the error is now:
```
unbound variable: s.ob (hint: did you mean one of:
  s .ob
?)
```

**Comment by olynch** [comment]
OK, as long as the error message is reasonable, I'm happy with this design decision! I do quite like the symmetry between constructors and destructors in narya. But does `x .y` bind as tightly as `x.y`? I find myself putting parentheses around `x .y` to make sure it will associate properly, perhaps just out of paranoia.

If you haven't considered using `/` for namespaces, it could be a reasonable choice I think. It perhaps would make the distinction between namespaces and field access more clear. Of course, it would conflict with the use of `/` for division... but I think `//` is a reasonable operator for that.

**Comment by olynch** [comment]
For instance,

```
def Assoc (c: Cat) : Type :=
  let ob := c .ob in
  let hom := Id ob in
  let cmp := c .compose in
  (x y z w : ob) -> (f : hom x y) -> (g : hom y z) -> (h : hom z w) ->
   Id (Id ob) x y f z w h ((cmp x y z f g) .diff) ((cmp y z w g h) .diff)
```

parses,

but

```
def Assoc (c: Cat) : Type :=
  let ob := c .ob in
  let hom := Id ob in
  let cmp := c .compose in
  (x y z w : ob) -> (f : hom x y) -> (g : hom y z) -> (h : hom z w) ->
   Id (Id ob) x y f z w h (cmp x y z f g) .diff (cmp y z w g h) .diff
```

does not, whereas in most programming languages, using `(cmp x y z f g).diff` would bind clearly.

**Comment by mikeshulman** [comment]
No, `x .y` does not "bind as tightly" as `x.y`: since `x.y` is not an operator but a single identifier, whereas `x .y` binds like a function application.  So `x .y z` means `(x .y) z`, but `x y .z` means `(x y) .z`.

**Comment by mikeshulman** [comment]
It makes sense if you think in terms of elimination spines: "applying a function to an argument" and "projecting out a field" are both elimination operations, so if you start with a single object `x` you can do a sequence of those things to it without parentheses: `x a .b c .d`.  But if you want to do an elimination operation on one of the *arguments* of `x`, you have to parenthesize it.  So what you should really write is
```
def Assoc (c: Cat) : Type :=
  let ob := c .ob in
  let hom := Id ob in
  let cmp := c .compose in
  (x y z w : ob) -> (f : hom x y) -> (g : hom y z) -> (h : hom z w) ->
   Id (Id ob) x y f z w h (cmp x y z f g .diff) (cmp y z w g h .diff)
```

**Comment by olynch** [comment]
> It makes sense if you think in terms of elimination spines: "applying a function to an argument" and "projecting out a field" are both elimination operations, so if you start with a single object `x` you can do a sequence of those things to it without parentheses: `x a .b c .d`. But if you want to do an elimination operation on one of the _arguments_ of `x`, you have to parenthesize it. So what you should really write is
> 
> ```
> def Assoc (c: Cat) : Type :=
>   let ob := c .ob in
>   let hom := Id ob in
>   let cmp := c .compose in
>   (x y z w : ob) -> (f : hom x y) -> (g : hom y z) -> (h : hom z w) ->
>    Id (Id ob) x y f z w h (cmp x y z f g .diff) (cmp y z w g h .diff)
> ```

OK, that's not too bad, I'll see if I can get used to this.

**Comment by mikeshulman** [comment]
I am very happy to be getting feedback on the parser, by the way.  Please do continue to let me know what you think.

Of course, regarding `/`, another option would be to go full Agda and require spaces around all operators.  But I just don't really like that: I want to be able to write `x:A` and `A->B` and `x+y`.

On the other hand, there's a question of whether division even makes sense as a binary operator in a proof assistant, since you need to deal with the nonzeroness of the divisor somehow, and I could see an argument that that means it *shouldn't* have a notation that's parallel with `+`, `-`, and `*`.

**Comment by olynch** [comment]
I had a similar thought: in a proof assistant namespacing is a much more frequent operation than division!

**Comment by mikeshulman** [comment]
Well, I do want Narya to also be usable as a programming language, and the vast majority of programming languages use `/` for division.  On the other hand, even in ordinary programming, division is less common than the other arithmetic operations, and it's sufficiently subtle that it may not be a bad thing for a programmer to have to stop and think about exactly what kind of division they mean and use the appropriate operator or function.

If Narya did use `/` for namespacing, my inclination would be that `//` should be a parse error (empty namespace component).  For division we have other options like `∕` (0x2215 DIVISION SLASH) and `÷` (0xF7 DIVISION SIGN).

Another possible disadvantage of allowing `a/b.c` to parse as `a/b .c`, presumably with infinitely tight binding, is that it might make people *more* inclined to expect `f (g a).b` to parse as `f ((g a).b)` rather than the correct `(f (g a)) .b`.  And, to be honest, `a/b.c` *looks* to me like `a/(b.c)`, although I suppose I could probably get used to it.

**Comment by mikeshulman** [comment]
More data points:
- Agda behaves like Narya currently does: dots for both namespacing and fields, while fields have to be separated by a space before but not after, `foo.bar .baz`.  Field projection binds like function application, as in current Narya.
- Coq also uses dots for both, but requires fields to be parenthesized, which allows unambiguous combination without spaces: `Foo.bar.(baz)`.  There can be spaces inside the parentheses, but not between the dot and the open-parenthesis: `Foo.bar.( baz )` parses  but `Foo.bar. (baz)` doesn't.  (Coq *also* uses dots as a command terminator, apparently whenever it's followed by whitespace.)  Field projections bind tighter than function application.
- Lean uses dots for both, with no spaces allowed, binding tighter than function application.  Ambiguities appear to be resolved in favor of objects: in fact it seems from my experiments that if there is a namespace `foo.bar` then it hides any object named `foo.bar` entirely.
- Idris uses dots for both, with spaces allowed before the dot of a field projection, binding tighter than function application.  I'm not sure about ambiguities; the [examples](https://idris2.readthedocs.io/en/latest/reference/records.html) show `(Main.pt).x` but not what `Main.pt.x` would mean.
- OCaml uses dots for both, with spaces on both sides allowed but not required.  Namespaces are all modules, which are required to start with an uppercase letter, while object and field names are required to start with a lowercase letter, so there is no possible ambiguity.  Field projections bind tighter than function application.
- Haskell uses dots for both, *and* for infix function composition.  According to the [proposal](https://ghc-proposals.readthedocs.io/en/latest/proposals/0282-record-dot-syntax.html), whitespace after the dot turns it into function composition;  if `a.b.c` is ambiguous, it's resolved in favor of object `c` in module `a.b`, the field projection is obtainable with `(a.b).c`; and field projections bind tighter than function application.
- Python uses dots for both, with spaces allowed but not required.  But I believe that in Python modules are just a special kind of object, so both "meanings of dot" are really the same thing.  Function calls use parentheses, so there is no question of precedence.
- Java uses dots for both, and (according to ChatGPT, at least) the compiler will complain if it encounters an ambiguous expression.  Function calls use parentheses.
- The most common symbol used for namespacing other than a dot [seems to be](https://en.wikipedia.org/wiki/Fully_qualified_name) `::`.  We should probably avoid this in a type-theory-based proof assistant, although I suppose it might be possible in theory since the other uses of a colon would never have two of them in a row (except for crisp variables in a modal type theory).  I don't know of any languages that use `/` for namespacing.

**Comment by mikeshulman** [comment]
However, despite the weight of precedent for field projection binding tighter than function application, I still feel like this is wrong.  For instance, in a language with parenthesized function calls like Java, one frequently finds an idiom like
```
object.methodOne(x, y, z)
  .methodTwo(a, b)
  .methodThree(c, d, e)
  .methodFour()
```
to call a sequence of methods on each other's outputs.  In Agda and current Narya, you can write the same thing even more simply without the parentheses:
```
object .methodOne x y z
  .methodTwo a b
  .methodThree c d e
  .methodFour
```
But in a language with application by juxtaposition but where field projection binds tighter than function application, you have to write lots of silly parentheses:
```
(((object.methodOne x y z)
  .methodTwo a b)
  .methodThree c d e)
  .methodFour
```

**Comment by mikeshulman** [comment]
Another advantage to keeping `/` as an ASCII operator symbol is that it can then be used as part of other multi-character operators like `/=`, `/\`, and `\/`.  Plus, *conceptually* a namespace is a lot like a giant record, even if that isn't literally true the way it is in Python; so it makes sense to use the same character for both namespacing and field projections.  So right now I'm inclined to keep the current precedence, and keep dot for both namespaces and projections.

However, I'm thinking about Haskell's approach of allowing `a.b.c`  to fall back to `a.b .c` if no object named `a.b.c` exists.

**Comment by olynch** [comment]
> However, I'm thinking about Haskell's approach of allowing `a.b.c` to fall back to `a.b .c` if no object named `a.b.c` exists.

Would this bind in the same way as `.` currently does? E.g., `a.b.c` is `(a.b .c)`, not `a.b .c`? Because otherwise it could be quite confusing for stuff like `f x.y`.

**Comment by mikeshulman** [comment]
Yes, the spaceless version would bind tighter than function application.  I agree that otherwise, `f x.y` would be extremely confusing.  But I am concerned that there's also a potential for confusion with `f x.y` parsing as `f (x.y)` but `f x .y` parsing as `(f x).y`, though.

**Comment by olynch** [comment]
My feeling is that `f x .y` is sufficiently unfamiliar to a typical programmer that the behavior of `(f x) .y` can be learned. And in any case, `f x.y` *already* parses as `f (x.y)`, it's just that it must be a namespacing `.` not a field access. So the distinction between `f x.y` and `f x .y` is already in the grammar.

**Comment by mikeshulman** [comment]
I added the lots-of-silly-parentheses example to the README, and opened #32 to discuss spaceless projections, so I'm closing this issue.
