### ISSUE TITLE
Diagnostic spans include whitespace after the error

### ISSUE THREAD

**Issue by TOTBWF** [mikeshulman/narya#3]
Whenever `narya` reports a diagnostic, it will print out all trailing whitespace in the diagnostic message. This can lead to some difficult to read diagnostics.

As a concrete example, consider the following (obviously wrong) bit of `narya` code.
```
def problem : Type := alskdfjlkadjf
{`
This is a very long comment.
`}
```

Narya will report the diagnostic with the entire comment underlined.

```
 ￫ error[E0300]
 ￭ whitespace.ny
 1 | def problem : Type := alskdfjlkadjf
 2 | {`
 3 | This is a very long comment.
 4 | `}
 5 | 
   ^ unbound variable: alskdfjlkadjf
   ```

**Comment by mikeshulman** [comment]
Yes, I've noticed this too.  Presumably the placement of the `located` parsing combinators needs to be adjusted so that locations don't include trailing whitespace.  (As you may have noticed, the parser is a bit weird because comments are not stripped out by the lexer, since I wanted to be able to use the output of the parser to print the code reformatted without losing the comments.  This sort of problem is a side effect of that.)
