### ISSUE TITLE
feature: `absurd` that lives in `check`

### ISSUE THREAD

**Issue by TOTBWF** [mikeshulman/narya#4]
Right now, eliminating out of the empty type requires the user to provide a motive, which can get extremely large after a couple of rounds of display. This would be solved by unification, but as a stop-gap measure we could add a built-in empty type with an eliminator that lived in `check`; this would remove ~100 lines of code from our current formalization!

**Comment by mikeshulman** [comment]
I assume you mean "eliminating out of the empty type".  (-:

Would it also solve your problem if we had matches against arbitrary terms that could appear in arbitrary locations?  I think then you could get the effect of `absurd e` with `match e [ ]`.

I went ahead and implemented matches against arbitrary terms in case trees, which is something I've been meaning to do.  When matching against a non-variable, of course, the output type doesn't get refined, but this shouldn't matter for the empty type.  This might help you some, depending on how often your `absurd`s are direct case tree leaves versus nested more deeply in terms.  Allowing matches in arbitrary locations would be trickier since it would require `match`es in values; if this change doesn't help you enough then I'll consider a checking `absurd`.

**Comment by TOTBWF** [comment]
Yes, I did mean the empty type, nice catch 😅 

The most common pattern we've been encountering is that you have some proof of false underneath a lambda that itself is a direct case tree leaf, though there are definitely cases that are direct leaves, so this is already quite an improvement!

**Comment by mikeshulman** [comment]
I tried experimenting with matches in arbitrary locations, in a branch at https://github.com/mikeshulman/narya/tree/kinetic-match.  It compiles and works on at least one example, but I haven't stress-tested it at all yet, and this is a fiddly change, which is why I haven't merged it to master yet.  But if you want to give it a try, feel free.

**Comment by TOTBWF** [comment]
Cheers! Will give it a go

**Comment by mikeshulman** [comment]
Actually, I forgot it's not even completely implemented: readback is missing, so in particular you can't print terms that include kinetic matches.
